### ISSUE TITLE
Add flag to force the default scheme

### ISSUE THREAD

**Issue by VojtechVitek** [PuerkitoBio/purell#11]
Hi,
I'd like a flag to force the default scheme (eg. `http`) when no scheme was given.

```go
str, _ := purell.NormalizeURLString("example.com/foo.html", purell.FlagsForceDefaultHttpScheme)

if str == "http://example.com/foo.html" {
  // cool, I have "http" default scheme set now
}
```

Would it make sense? If yes, I'd be glad to submit a patch.

**Comment by PuerkitoBio** [comment]
I'm not sure, because if a relative path is provided, it will turn it into a(potentially wrong) absolute path, plus it's not obvious that http should be the default.

**Comment by VojtechVitek** [comment]
`"example.com"` ... seems to me more like a domain name, than a relative path. But I might be wrong, as the default `net/url` pkg parses it as a Path instead :)

Well, http doesn't need to be the only default value. Consider other flags, like `"FlagsForceDefaultHttpsScheme"` etc.

**Comment by PuerkitoBio** [comment]
It looks like a domain name, but given a non-rooted path, the parser has no
way to know if it is a domain or a path (it's also a valid relative path).
That's why I'm reluctant to add this feature (this and the default scheme,
which means two flags just for http - there are other schemes). So I think
I'll pass on this feature request, sorry.

**Comment by VojtechVitek** [comment]
No worries, thanks anyway.
