### ISSUE TITLE
Remove Multiple Leading Slashes

### ISSUE THREAD

**Issue by frankgreco** [PuerkitoBio/purell#24]
using `v1.1.0`

```go
result, _ := purell.NormalizeURLString("///foo///bar///", purell.FlagRemoveDuplicateSlashes | purell.FlagRemoveTrailingSlash)
// result is //foo/bar/
```
To get around this, I just use the following function:

```go
func removeDupLeadingSlashes(path string) string {
  if len(path) < 1 {
    return "/"
  }
  var buffer bytes.Buffer
  var i int
  buffer.WriteString("/")
  for i=0; i<len(path); i++ {
    if path[i] == '/' {
      continue
    }
    break
  }
  buffer.WriteString(path[i:])
  return buffer.String()
}
```

**Comment by mna** [comment]
Hello Frank,

Looks like this is already fixed in master, I added this test case and it returns `/foo/bar` as expected. Actually I even tried it on 1.1.0 and it works too, are you sure you're running the exact same code snippet as in the issue? And can you double-check the purell version?

Thanks,
Martin
